### ISSUE TITLE
Theme names must start with a lowercase letter

### ISSUE THREAD

**Issue by book** [perlancar/perl-Acme-MetaSyntactic-WordList#1]
Behaviour modules (like [Acme::MetaSyntactic::MultiList](https://metacpan.org/pod/Acme::MetaSyntactic::MultiList)) start with an uppercase letter, while theme modules start in lowercase, [as documented](https://metacpan.org/pod/Acme::MetaSyntactic#THEMES).

Having your module start with an uppercase will prevent it from being automatically discovered (e.g. by [Bot::BasicBot::Pluggable::Module::MetaSyntactic](https://metacpan.org/pod/Bot::BasicBot::Pluggable::Module::MetaSyntactic)).

**Comment by perlancar** [comment]
Yup, AM:WordList is a base class, not actual theme. I've added a description for it.

**Comment by book** [comment]
Sorry about that, I should have read the code instead of assuming. :-)

**Comment by book** [comment]
And congratulations on being the first person besides me to write a behaviour module for Acme::MetaSyntactic.

**Comment by perlancar** [comment]
Thanks :)
